AWSTemplateFormatVersion: 2010-09-09
Description: |
  The AWS CloudFormation template for creating Cloudformation execution role to be used by
  Cloudformation Service to create resources defined by serverless.yml.
  This role is passed to cloudformation service by Cross Account Role
Resources:
  CFExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cf-execution-role-serverless
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole

  CFExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allows pipeline in TOOLS account to deploy API Gateway, Lambda
      ManagedPolicyName: cf-execution-policy-serverless
      Roles:
        - !Ref CFExecutionRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: IAMRolesPermissions
            # Needed for creating Roles for Lambdas, EC2 instances and other services
            Effect: Allow
            Action:
              - iam:Get*
              - iam:List*
              - iam:*Role*
              - iam:CreatePolicy
              - iam:DeletePolicy
              - iam:*PolicyVersion*
              - iam:*InstanceProfile*
            Resource: '*'
          - Sid: S3FullAccess
            # To Get and Put deployment artifacts in serverless deployment bucket
            Effect: Allow
            Action:
              - s3:*
            Resource: '*'
          - Sid: CloudFormationFullAccess
            # To create CF stack for serverless deployment
            Effect: Allow
            Action:
              - cloudformation:*
            Resource: '*'
          - Sid: ApiGatewayFullAccess
            # API Gateway
            Effect: Allow
            Action:
              - apigateway:*
            Resource: '*'
          - Sid: LambdaFullAccess
            # Lambda
            Effect: Allow
            Action:
              - lambda:*
            Resource: '*'
          - Sid: DynamoDBFullAccess
            # DynamoDB
            Effect: Allow
            Action:
              - dynamodb:*
            Resource: '*'
          - Sid: Cloudwatch
            # To access cloudwatch logs
            Effect: Allow
            Action:
              - cloudwatch:*
              - logs:*
              - events:*
            Resource: '*'

Outputs:
  OutCFExecutionRole:
    Description: CloudFormation Execution Role ARN
    Value: !GetAtt CFExecutionRole.Arn
    Export:
      Name: Serverless-CFExecutionRoleArn
  OutCrossAccountDeploymentPolicy:
    Description: CloudFormation Execution Policy ARN
    Value: !Ref CFExecutionPolicy
    Export:
      Name: Serverless-CFExecutionPolicyArn